### ISSUE TITLE
FILTER_SANITIZE_STRING constant is deprecated in PHP 8.1

### ISSUE THREAD

**Issue by dvdheiden** [FabianBeiner/Todoist-PHP-API-Library#17]
This constant is currently used in, for example, the `TodoistSectionsTrait`.  The `FILTER_SANITIZE_STRING` is deprecated in PHP 8.1:

> Deprecated as of PHP 8.1.0, use [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php) instead.

Source: https://www.php.net/manual/en/filter.filters.sanitize.php

But when I look at the documentation of the `FILTER_SANITIZE_STRING` it does:

> Strip tags and HTML-encode double and single quotes, optionally strip or encode special characters.

So the suggested replacement has a different behavior as `htmlspecialchars` does not strip the tags.

I can create a PR, but want to discuss the solution first. I think in this case a `strip_tags` might be sufficient, but then the "HTML-encode double and single quotes" is missing. What do you think?

**Comment by FabianBeiner** [comment]
Good question, @dvdheiden. While I agree that `strip_tags` might be a good replacement here, I think we need to take a step back. Todoist actually allows your project to have tags (e.g., `<script>Projectname</script>'`). So, who are we to judge if someone wants to name its project like that? ;) Furthermore, it seems like Todoist will rename the project according to their filters anyway. 

That being said, how about simply replacing it with `FILTER_UNSAFE_RAW`? This could be the simplest solution.

**Comment by dvdheiden** [comment]
The `FILTER_UNSAFE_RAW` does nothing without any additional options. If Todoist already sanitizes the value, we could consider to just remove `$content = filter_var($content, FILTER_SANITIZE_STRING);` line?

**Comment by FabianBeiner** [comment]
Yeah, that is true. Currently, I don't see a reason why we would need that filter part then, yes.

**Comment by dvdheiden** [comment]
Ok, shall I create a PR for this?

**Comment by FabianBeiner** [comment]
Closed by #18
