### ISSUE TITLE
REST API (v1) is deprecated

### ISSUE THREAD

**Issue by FabianBeiner** [FabianBeiner/Todoist-PHP-API-Library#19]
I just stumbled on the following information at https://developer.todoist.com/rest/v1/#overview:

> **DEPRECATED**: This version of the REST API (v1) is deprecated and will be removed on Nov 30. Please refer to the [v2 documentation](https://developer.todoist.com/rest/v2).

This means, this script will break on November 30th. However, I can't promise I'll find the time to fix anything before.

**Comment by Valkyrie00** [comment]
Hi @FabianBeiner, as first i would say thank you for you work on this library, and also I would ask to u if there are some news about the migration to v2.
Is there any chance to see v2 implemented before Nov. 30th?

Thank you so much!

**Comment by FabianBeiner** [comment]
Yes, I actually have it planned. But I simply can't _promise_ it right now.

**Comment by Valkyrie00** [comment]
Hi @FabianBeiner, i opened a dedicated pull request about that, let me now what do you think about it :)

**Comment by FabianBeiner** [comment]
Thank you so much, @Valkyrie00! That looks great! :)
