### ISSUE TITLE
Ask new tag to match V2 API

### ISSUE THREAD

**Issue by Valkyrie00** [FabianBeiner/Todoist-PHP-API-Library#21]
Hi @FabianBeiner, thanks for the approval of my PR. Then i'm here to ask if can you create a new tag  about this implementation.
Thank you so much :).

**Comment by FabianBeiner** [comment]
Please give me a few days, @Valkyrie00. I'm planning to release this (and probably some smaller changes) as v2.0 these days. 🤞🏻

**Comment by Valkyrie00** [comment]
Perfect! Thank you so much!! 😁

**Comment by FabianBeiner** [comment]
https://github.com/FabianBeiner/Todoist-PHP-API-Library/releases/tag/v2.0.0
