### ISSUE TITLE
Exceptions - 401 in particular

### ISSUE THREAD

**Issue by lipkau** [FabianBeiner/Todoist-PHP-API-Library#7]
Hello.

_first of all, thank you for this package! cool stuff :-)_

I got to the point where I am implementing the exceptions of the APIs I am using.
But I am now stuck with the problem:
> How can I identify if the case where the access_token was invalidated?

For the other APIs I am consuming, I am checking for 401 responses.
What is the recommended way here?

```php
if (!$client->getAllProjects()) {
  removePairing();
}
```

I was expecting something more in the likes of

```php
try {
    $client->getAllProjects();
} catch (\FabianBeiner\Todoist\ResponseForbidden $e) {
    removePairing();
}
```

**Comment by FabianBeiner** [comment]
Hey @lipkau,

Thanks for the kind words!

At the moment, I did not consider the scenario that the Token gets changed while the script is running. This is because it's not an OAuth token, but a manually and one time generated one. While people might regenerate one, it was not likely, in my opinion, that this happens while the script does anything.

So for now, I'd recommend the following:

```php
try {
    $Todoist = new FabianBeiner\Todoist\TodoistClient('API_TOKEN');

    if ( ! $Todoist->getAllProjects()) {
        throw new  Exception('The API token seems invalid.');
    }
} catch (Exception $e) {
    echo 'An error occurred: ' . $e->getMessage();

    return false;
}
```

This is not elegant, but it might be a solution for now. I'll have to add checks anytime soon.

**Comment by lipkau** [comment]
Thank you.

To clarify, I am not counting on the token being invalidated during runtime.
But rather having the app use the [OAuth Authorization Code Flow](https://developer.todoist.com/sync/v8/#oauth) for pairing with todoist, storing the access_token in a DB and using it later.

the token can get invalidated by
* the [App registered at todosit](https://developer.todoist.com/appconsole.html) being deleted
* the app owner invalidating all tokens  
![image](https://user-images.githubusercontent.com/4992870/71644305-a0bb5600-2cc6-11ea-843c-25762940c1a5.png)
* the user removing the integration with the app https://todoist.com/prefs/integrations

**Comment by FabianBeiner** [comment]
I am using the REST API, not the Sync API, so there is no OAuth, just a personal API token. ;)

**Comment by lipkau** [comment]
I know. But the REST API can use the same OAuth as the sync API:

https://developer.todoist.com/rest/v1/#authorization links to https://developer.todoist.com/sync/v8/#oauth

![image](https://user-images.githubusercontent.com/4992870/71644749-e7f91500-2ccd-11ea-9ace-cc6d822ef52b.png)

**Comment by FabianBeiner** [comment]
Yes, but as said, this class does not.

**Comment by lipkau** [comment]
It does!
I can show you, if you are interested

**Comment by FabianBeiner** [comment]
Of course, go ahead!

**Comment by lipkau** [comment]
do you want a sample repo which you have to clone, setup and create a todoist app to test?
I can also show you via discord or zoom

**Comment by FabianBeiner** [comment]
Wait, just to be sure: 

You implemented that OAuth thingy yourself, right?

**Comment by lipkau** [comment]
correct

**Comment by FabianBeiner** [comment]
Ahhh! Well, you have to implement this for yourself at the moment, as my official library does not support this. But I'm looking forward to the updated library! :)

**Comment by lipkau** [comment]
For anyone interested in this: @FabianBeiner 's suggestion on how to solve this did not take into account that an empty array is also considered false. Therefore, I recommend using this instead:

```php
try {
    $Todoist = new FabianBeiner\Todoist\TodoistClient('API_TOKEN');

    if ( ! is_array($Todoist->getAllProjects())) {
        throw new  Exception('The API token seems invalid.');
    }
} catch (Exception $e) {
    echo 'An error occurred: ' . $e->getMessage();

    return false;
}
```
