### ISSUE TITLE
The code example on readme.md is wrong

### ISSUE THREAD

**Issue by ghost** [FabianBeiner/Todoist-PHP-API-Library#8]
Code example on readme.md is wrong.

I get this error:
PHP Fatal error:  Uncaught Error: Class 'FabianBeiner\Todoist\Todoist' not found 

So the code on readme.md is this:
$Todoist = new FabianBeiner\Todoist\Todoist('YOUR_API_TOKEN');
Should be this:
$Todoist = new FabianBeiner\Todoist\TodoistClient('YOUR_API_TOKEN'); 

Maybe tweak the readme, otherwise great work and thank you!

**Comment by FabianBeiner** [comment]
Thank you!
