### ISSUE TITLE
Unable to manipulate curl

### ISSUE THREAD

**Issue by lipkau** [FabianBeiner/Todoist-PHP-API-Library#9]
the change to the signature of `TodoistClient` constructor messed with my setup:

I suppress the ssl verification when running in debug mode. This is because when running the app on my local machine, the SSL will always fail and curl returns 
> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 

I use it like this:
```
new TodoistClient($serviceCode->access_token, ['verify' => !env('APP_DEBUG', false)]);
```

I would like to propose to have the `$config = []` from version < 1.0 as the 3rd argument to the constructor.
https://github.com/FabianBeiner/Todoist-PHP-API-Library/commit/7e95c1616bbb9e148ba15d2c6b6771ab008cc1d3#diff-aec6dcf89dc5fd658ec91e8310e54ad6de5c9f2da70a8c65db615ff38a8b7625L44-R56

**Comment by FabianBeiner** [comment]
I really don't remember why I removed that option. Anyway, I added it again as the third parameter. 👍
